development:
  adapter: postgresql
  encoding: unicode
  database: dummy_development
  pool: 5
  username: postgres
  #password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: dummy_test
  pool: 5
  username: postgres
  #password:
  min_messages: WARNING
  host: localhost
